#!/bin/bash

IMPORT_PATH=/Users/jb/code/legendary-happiness/share/niteworks/elixir/tweets/data/output/*.json
for i in $IMPORT_PATH; do
    mongoimport --db niteworks --collection tweets --file $i
done
